# provide the environments needed
# NODE_ENV=production

SOCKET_CLIENT_PORT=3000
NODE_CLIENT_PORT=3200
SOCKET_SERVER_PORT=3300
VM_IP=192.168.10.4

PUB_SOCKET_SERVER_URL=http://socket-server.v3.lcl
PUB_NODE_CLIENT_URL=http://node-client.v3.lcl
PUB_SOCKET_CLIENT_URL=http://socket-client.v3.lcl

INT_SOCKET_SERVER_URL=http://$VM_IP:$SOCKET_SERVER_PORT
INT_NODE_CLIENT_URL=http://$VM_IP:$NODE_CLIENT_PORT
INT_SOCKET_CLIENT_URL=http://$VM_IP:$SOCKET_CLIENT_PORT


LCL_SOCKET_SERVER_URL=http://127.0.0.1:$SOCKET_SERVER_PORT
LCL_NODE_CLIENT_URL=http://127.0.0.1:$NODE_CLIENT_PORT
LCL_SOCKET_CLIENT_URL=http://127.0.0.1:$SOCKET_CLIENT_PORT

MGO_URL=mongodb+srv://metric-flow:f87yKs2mlHQ9BDoI@cluster0.mcmyi9z.mongodb.net/